Repository smarr/ReBench, pull requests merged in 2024-07, with the labels that each got.

#239 Fix cset_path issue, update readme, reenable pylint in CI
  .github/workflows/ci.yml
  README.md
  rebench/denoise.py
  rebench/executor.py
  rebench/rebenchdb.py
  rebench/tests/features/issue_42_test.py
Labels: Maintenance

#240 Expand ~ in paths for cmdline_for_next_invocation
  .github/workflows/ci.yml
  rebench/executor.py
  rebench/model/benchmark_suite.py
  rebench/model/executor.py
  rebench/model/run_id.py
  rebench/tests/model/runs_config_test.py
  rebench/tests/small_expand_user.conf
Labels: Feature

#246 Added missing machine column heading for summary table
  rebench/reporter.py
Labels: Bug

#245 Handle running on bare-bone setup more gracefully
  rebench/environment.py
Labels: Bug
